export {
  COMMAND_TEMPLATE_LIBRARY_STATE_KEY,
  PLACEHOLDER_PATTERN,
  SNIPPET_LIBRARY_STATE_KEY,
  SnippetValidationError,
  checkCommandTemplateRunScope,
  checkSnippetRunScope,
  createSnippetId,
  deleteCommandTemplate,
  deleteSnippet,
  expandCommandTemplateLines,
  expandSnippetBody,
  extractPlaceholderNames,
  filterCommandTemplatesByScope,
  filterSnippetsByScope,
  getCommandTemplate,
  getSnippet,
  normalizeCommandTemplate,
  normalizeSnippet,
  parseCommandTemplateLibrary,
  parseSnippetLibrary,
  resolvePlaceholders,
  scopeLabel,
  snippetPaletteCommandId,
  snippetToPaletteCommand,
  splitCommandLines,
  upsertCommandTemplate,
  upsertSnippet,
  validateSnippet,
} from './model';
export type {
  CommandTemplateEntry,
  CommandTemplateInput,
  CommandTemplateRunScopeCheck,
  CommandTemplateScopeFilter,
  SnippetEntry,
  SnippetExpansionContext,
  SnippetInput,
  SnippetKind,
  SnippetPaletteCommandDescriptor,
  SnippetRunScopeCheck,
  SnippetScope,
  SnippetScopeFilter,
} from './types';
